In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

In [3]:
df.columns = ['color', 'size', 'price', 'classlabel']

In [4]:
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [5]:
size_mapping = {'XL': 3, 'L': 2, 'M': 1}

In [6]:
df['size'] = df['size'].map(size_mapping)

In [7]:
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [8]:
import numpy as np

In [9]:
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [10]:
class_mapping

{'class1': 0, 'class2': 1}

In [11]:
df['classlabel'] = df['classlabel'].map(class_mapping)

In [12]:
df

color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [13]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}

In [14]:
df['classlabel'] = df['classlabel'].map(inv_class_mapping)

In [15]:
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
class_le = LabelEncoder()

In [18]:
y = class_le.fit_transform(df['classlabel'].values)

In [19]:
y

array([0, 1, 0])

In [20]:
class_le.inverse_transform(y)

array(['class1', 'class2', 'class1'], dtype=object)

In [21]:
X = df[['color', 'size', 'price']].values

In [22]:
color_le = LabelEncoder()

In [23]:
X[:, 0] = color_le.fit_transform(X[:, 0])

In [24]:
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder(categorical_features=[0])

In [29]:
ohe.fit_transform(X).toarray()

array([[  0. ,   1. ,   0. ,   1. ,  10.1],
       [  0. ,   0. ,   1. ,   2. ,  13.5],
       [  1. ,   0. ,   0. ,   3. ,  15.3]])

In [32]:
pd.get_dummies(df[['price', 'color', 'size']])

price  size  color_blue  color_green  color_red
0   10.1     1           0            1          0
1   13.5     2           0            0          1
2   15.3     3           1            0          0